//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApplicationv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Available
    {
        public int CourseId { get; set; }
        public int SeatsTaken { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Waitlist { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
