//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApplicationv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesTaught
    {
        public int ProfId { get; set; }
        public int CourseId { get; set; }
    
        public virtual ClassTime ClassTime { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
